BasedOnStyle: LLVM
IndentWidth: 4
ColumnLimit: 100
SpaceBeforeParens: Never
AllowShortIfStatementsOnASingleLine: WithoutElse
AllowShortLoopsOnASingleLine: true
NamespaceIndentation: None
SortIncludes: Never
